### ISSUE TITLE
Missing recipe in 1.15.2

### ISSUE THREAD

**Issue by katubug** [Ephys/minecraft-magic-feather#11]
Hi! I commented earlier on the mod page, but now that I've had time to double check that I didn't make an error, I'm gonna put in an issue. I am using:

MC 1.15.2
Forge 31.2.30
JEI 6.0.2.12
Magic Feather 2.2.2
CookieCore 2.1.2-37c5343

In an instance with just those mods, I am able to replicate the fact that no recipe seems to be added. Both right and left clicking in JEI bring up nothing, same with "u" and "r" hotkeys (I know it wouldn't be "u" but it never hurts to double check). I also checked in a crafting grid using the recipe you gave me in the mod page comments:

![2020-07-03_16 13 11](https://user-images.githubusercontent.com/20935286/86497714-5899f080-bd48-11ea-8f78-bc2425f147b6.png)

As you can see, it doesn't seem to work. For me, this isn't really a HUGE issue because I was probably going to edit the recipe using crafttweaker anyway. However, since it doesn't seem to be intended behavior, I thought I'd let you know! Thanks very much for your time!

**Comment by xAlicatt** [comment]
Was coming to report this as well.

**Comment by ephys** [comment]
I found some time to work on this and figured out the issue, the recipes json files have been moved from assets to the data folder somewhere between 1.12 and 1.15

I'm releasing a fixed version as we speak before moving on to 1.16

Edit: You can now find it on curseforge, should be approved soon - https://www.curseforge.com/minecraft/mc-mods/magic-feather/files/3043462
