### ISSUE TITLE
missing language javafml:33

### ISSUE THREAD

**Issue by Pentasis** [Ephys/minecraft-magic-feather#14]
Your version 3.1.0 shows up as compatible for MC 1.16.1 (in twitch). However, it will give an error stating it needs language javafml:33 or higher (I'm using forge 32.0.108).

**Comment by ephys** [comment]
Fixed :) https://www.curseforge.com/minecraft/mc-mods/magic-feather/files/3097412

**Comment by prabhdeep20** [comment]
I downloaded journey maps in 1.15.2 version but its showing you need javafml:33 to running.
Please solution

**Comment by ephys** [comment]
This isn't the JourneyMap repository
