### ISSUE TITLE
Creative flight buggy movement

### ISSUE THREAD

**Issue by jajajafeti** [Ephys/minecraft-magic-feather#15]
Hey I play the 1.16.2 - 1.16.4 (3.1.0) version on 
Minecraft 1.16.5
Forge 36.0.42

Now I rly wanted to use this mod, but the creativ flight (not only with the feather also in creative mode) gets buggy when you double tap the space bar (start or stop flight).
In each Video I only double tap once at the start and then it gets *shakey*.

https://user-images.githubusercontent.com/61298096/109192020-0efa8c00-7797-11eb-8be9-409ad4568fa5.mp4

https://user-images.githubusercontent.com/61298096/109192028-115ce600-7797-11eb-8730-3891cd8efcf8.mp4

**Comment by jajajafeti** [comment]
Okay okay, I was sure it is this mod caus I tested it without and it seemd fine, but I tested it too little, it was another mod. Soory.

**Comment by ephys** [comment]
No worries :) Glad to hear you found the culprit
