### ISSUE TITLE
Config option for slow fall

### ISSUE THREAD

**Issue by DarkYuan** [Ephys/minecraft-magic-feather#19]
Could the slow fall feature be an option please? It leads to floaty hops for the two seconds after touching down. And in most cases (in the version prior), the fall from going out of range doesn't deal fall damage anyway.

**Comment by ephys** [comment]
Yeah after testing it more I also prefer the old behavior of just negating the fall damage and falling as quickly as possible. I've put it behind a config option, and reduced the duration of the slow fall effect

**Comment by ephys** [comment]
Released as part of https://www.curseforge.com/minecraft/mc-mods/magic-feather/files/3885425
