### ISSUE TITLE
[Suggestion] Baubles Support

### ISSUE THREAD

**Issue by MasterEnderman** [Ephys/minecraft-magic-feather#4]
Could you add Baubles Support so you don't need to have the feather in the inventory?

**Comment by ephys** [comment]
I can, but I'm not sure what kind of bauble a feather is

**Comment by MasterEnderman** [comment]
Maybe for the body part, because the elytra goes in the chest plate slot normally? Or just let it go in any slot... Maybe make it even a config option so the player can decide that.

**Comment by MissPotato** [comment]
It might be culturally insensitive to make it into a headpiece, but I don't see any cultural implications of wearing it as a pendant or maybe a "shirt" clip.

**Comment by ephys** [comment]
Thanks for the suggestions :)

I think I'm gonna make it a config option for modpack makers and set it to Charm by default

Update: done
