### ISSUE TITLE
1.15.1 Crash on server load

### ISSUE THREAD

**Issue by Yamza** [Ephys/minecraft-magic-feather#8]
Added mod to server, server crashes on load with the attached error.

https://hatebin.com/nqqlwpilbj

magicfeather-1.15.1-2.2.0.jar Magic Feather 
Forge 30.0.39

**Comment by ephys** [comment]
Thanks for the report, I'll be pushing a fix to curseforge in a minute (testing outside of dev env first)

**Comment by ephys** [comment]
Here you go, file should be available in a few https://www.curseforge.com/minecraft/mc-mods/magic-feather/files/2859996
